name: http consistency tests

on:
  workflow_dispatch:
    inputs:
      spiced_commit:
        description: "spiced build commit"
        required: false
        type: string
      spicepod_path:
        description: "The spicepod file to test with"
        required: true
        type: string
      duration:
        description: "The test duration in seconds"
        required: true
        default: "3600"
        type: string
      payload_file:
        description: "Payload file"
        required: false
        type: string
      model:
        description: "Model name"
        required: false
        type: string
      embedding:
        description: "Embedding name"
        required: false
        type: string
      ready_wait:
        description: "How long (in seconds) to wait for spiced to start"
        required: true
        default: "30"
        type: string
      buckets:
        description: "The number of buckets to divide the test duration into"
        required: true
        default: 10
        type: number

jobs:
  run-http-consistency:
    name: Run http consistency tests
    runs-on: spiceai-runners
    timeout-minutes: 600
    steps:
      - name: Run details
        run: |
          echo "Running http overhead test with:"
          echo "  spiced_commit=${{ github.event.inputs.spiced_commit || 'latest trunk' }}"
          echo "  spicepod_path=${{ github.event.inputs.spicepod_path }}"
          echo "  duration=${{ github.event.inputs.duration }}"
          echo "  payload_file=${{ github.event.inputs.payload_file }}"
          echo "  model=${{ github.event.inputs.model }}"
          echo "  embedding=${{ github.event.inputs.embedding }}"
          echo "  ready_wait=${{ github.event.inputs.ready_wait }}"
          echo "  buckets=${{ github.event.inputs.buckets }}"

      - uses: actions/checkout@v4

      - name: Install MinIO
        run: |
          sudo apt update && sudo apt install wget -y
          sudo wget https://dl.min.io/client/mc/release/linux-amd64/mc -O /usr/local/bin/mc
          sudo chmod +x /usr/local/bin/mc
          mc alias set spice-minio ${{ secrets.MINIO_ENDPOINT }} ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}

      - name: Get latest trunk commit
        if: ${{ !github.event.inputs.spiced_commit }}
        run: |
          git fetch origin
          echo "SPICED_COMMIT=$(git rev-parse origin/trunk)" >> $GITHUB_ENV

      - name: Set SPICED_COMMIT from workflow input
        if: ${{ github.event.inputs.spiced_commit }}
        run: |
          echo "SPICED_COMMIT=${{ github.event.inputs.spiced_commit }}" >> $GITHUB_ENV

      - name: Download spiced from MinIO
        run: |
          mc cp spice-minio/artifacts/spiced/linux-x86_64/$SPICED_COMMIT/spiced_models_linux_x86_64.tar.gz spiced_models_linux_x86_64.tar.gz
          tar -xzf spiced_models_linux_x86_64.tar.gz
          sudo cp ./spiced /usr/local/bin/spiced

      - name: Build Testoperator
        uses: ./.github/actions/build-testoperator

      - name: Run model http consistency test
        if: ${{ github.event.inputs.model }}
        run: |
          testoperator run http-consistency \
            -s /usr/local/bin/spiced \
            -p ${{ github.event.inputs.spicepod_path }} \
            --ready-wait ${{ github.event.inputs.ready_wait }} \
            --model ${{ github.event.inputs.model }} \
            --disable-progress-bars \
            --duration ${{ github.event.inputs.duration }} \
            --payload-file ${{ github.event.inputs.payload_file }}
        env:
          SPICE_SECRET_OPENAI_API_KEY: ${{ secrets.SPICE_SECRET_OPENAI_API_KEY }}
          SPICE_SECRET_ANTHROPIC_API_KEY: ${{ secrets.SPICE_SECRET_ANTHROPIC_API_KEY }}
          SPICE_SECRET_XAI_API_KEY: ${{ secrets.SPICE_SECRET_XAI_API_KEY }}

      - name: Run embedding http consistency test
        if: ${{ github.event.inputs.embedding }}
        run: |
          testoperator run http-consistency \
            -s /usr/local/bin/spiced \
            -p ${{ github.event.inputs.spicepod_path }} \
            --ready-wait ${{ github.event.inputs.ready_wait }} \
            --embedding ${{ github.event.inputs.embedding }} \
            --disable-progress-bars \
            --duration ${{ github.event.inputs.duration }} \
            --payload-file ${{ github.event.inputs.payload_file }}
        env:
          SPICE_SECRET_OPENAI_API_KEY: ${{ secrets.SPICE_SECRET_OPENAI_API_KEY }}
          SPICE_SECRET_ANTHROPIC_API_KEY: ${{ secrets.SPICE_SECRET_ANTHROPIC_API_KEY }}
          SPICE_SECRET_XAI_API_KEY: ${{ secrets.SPICE_SECRET_XAI_API_KEY }}
